# Generated by Django 5.2.8 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(db_column='StudentID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50, verbose_name='نام')),
                ('lastname', models.CharField(db_column='LastName', max_length=50, verbose_name='نام خانوادگی')),
                ('birthdate', models.DateField(blank=True, db_column='BirthDate', null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=3, null=True, verbose_name='جنسیت')),
                ('nationalid', models.CharField(blank=True, db_column='NationalID', max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True, verbose_name='ایمیل')),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=15, null=True, verbose_name='شماره تماس')),
                ('enrollmentyear', models.TextField(blank=True, db_column='EnrollmentYear', null=True, verbose_name='سال ورود')),
                ('gpa', models.DecimalField(blank=True, db_column='GPA', decimal_places=2, max_digits=4, null=True, verbose_name='معدل')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجویان',
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
