# Generated by Django 5.2.8 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('alumniid', models.AutoField(db_column='AlumniID', primary_key=True, serialize=False)),
                ('graduationyear', models.TextField(blank=True, db_column='GraduationYear', null=True, verbose_name='سال فارغ\u200cالتحصیلی')),
                ('degree', models.CharField(blank=True, db_column='Degree', max_length=50, null=True, verbose_name='مدرک')),
                ('currentjob', models.CharField(blank=True, db_column='CurrentJob', max_length=100, null=True, verbose_name='شغل فعلی')),
                ('employer', models.CharField(blank=True, db_column='Employer', max_length=100, null=True, verbose_name='کارفرما')),
            ],
            options={
                'verbose_name': 'فارغ\u200cالتحصیل',
                'verbose_name_plural': 'فارغ\u200cالتحصیلان',
                'db_table': 'alumni',
                'managed': False,
            },
        ),
    ]
