# Generated by Django 5.2.8 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('societyid', models.AutoField(db_column='SocietyID', primary_key=True, serialize=False)),
                ('societyname', models.CharField(db_column='SocietyName', max_length=100, verbose_name='نام انجمن')),
                ('type', models.CharField(db_column='Type', max_length=6, verbose_name='نوع')),
                ('establishmentyear', models.TextField(blank=True, db_column='EstablishmentYear', null=True, verbose_name='سال تأسیس')),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'انجمن',
                'verbose_name_plural': 'انجمن\u200cها',
                'db_table': 'society',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocietyMembership',
            fields=[
                ('membershipid', models.AutoField(db_column='MembershipID', primary_key=True, serialize=False)),
                ('joindate', models.DateField(blank=True, db_column='JoinDate', null=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'verbose_name': 'عضویت در انجمن',
                'verbose_name_plural': 'عضویت\u200cهای انجمن',
                'db_table': 'societymembership',
                'managed': False,
            },
        ),
    ]
