# Generated by Django 5.2.8 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professorid', models.AutoField(db_column='ProfessorID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50, verbose_name='نام')),
                ('lastname', models.CharField(db_column='LastName', max_length=50, verbose_name='نام خانوادگی')),
                ('academicrank', models.CharField(db_column='AcademicRank', max_length=8, verbose_name='رتبه علمی')),
                ('department', models.CharField(blank=True, db_column='Department', max_length=100, null=True, verbose_name='دپارتمان')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True, verbose_name='ایمیل')),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=15, null=True, verbose_name='شماره تماس')),
                ('hiredate', models.DateField(blank=True, db_column='HireDate', null=True, verbose_name='تاریخ استخدام')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
                'db_table': 'professor',
                'managed': False,
            },
        ),
    ]
