# Generated by Django 5.2.8 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('accommodationid', models.AutoField(db_column='AccommodationID', primary_key=True, serialize=False)),
                ('dormitoryname', models.CharField(db_column='DormitoryName', max_length=100, verbose_name='نام خوابگاه')),
                ('roomnumber', models.CharField(blank=True, db_column='RoomNumber', max_length=10, null=True, verbose_name='شماره اتاق')),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True, verbose_name='ظرفیت')),
                ('location', models.CharField(blank=True, db_column='Location', max_length=100, null=True, verbose_name='موقعیت')),
            ],
            options={
                'verbose_name': 'خوابگاه',
                'verbose_name_plural': 'خوابگاه\u200cها',
                'db_table': 'accommodation',
                'managed': False,
            },
        ),
    ]
