# Generated by Django 5.2.8 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('sectionid', models.AutoField(db_column='SectionID', primary_key=True, serialize=False)),
                ('semester', models.CharField(db_column='Semester', max_length=7, verbose_name='ترم')),
                ('year', models.TextField(blank=True, db_column='Year', null=True, verbose_name='سال')),
                ('classroom', models.CharField(blank=True, db_column='Classroom', max_length=50, null=True, verbose_name='کلاس')),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True, verbose_name='ظرفیت')),
            ],
            options={
                'verbose_name': 'گروه درسی',
                'verbose_name_plural': 'گروه\u200cهای درسی',
                'db_table': 'classsection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(db_column='CourseID', primary_key=True, serialize=False)),
                ('coursename', models.CharField(db_column='CourseName', max_length=100, verbose_name='نام درس')),
                ('credits', models.IntegerField(db_column='Credits', verbose_name='تعداد واحد')),
                ('department', models.CharField(blank=True, db_column='Department', max_length=100, null=True, verbose_name='دپارتمان')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollmentid', models.AutoField(db_column='EnrollmentID', primary_key=True, serialize=False)),
                ('grade', models.DecimalField(blank=True, db_column='Grade', decimal_places=2, max_digits=4, null=True, verbose_name='نمره')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'db_table': 'enrollment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programid', models.AutoField(db_column='ProgramID', primary_key=True, serialize=False)),
                ('programname', models.CharField(db_column='ProgramName', max_length=100, verbose_name='نام رشته')),
                ('degreelevel', models.CharField(db_column='DegreeLevel', max_length=13, verbose_name='مقطع')),
                ('department', models.CharField(blank=True, db_column='Department', max_length=100, null=True, verbose_name='دپارتمان')),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True, verbose_name='مدت تحصیل (سال)')),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'رشته\u200cهای تحصیلی',
                'db_table': 'program',
                'managed': False,
            },
        ),
    ]
