# Generated by Django 5.2.8 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('researchid', models.AutoField(db_column='ResearchID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=200, verbose_name='عنوان پژوهش')),
                ('field', models.CharField(blank=True, db_column='Field', max_length=100, null=True, verbose_name='زمینه')),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True, verbose_name='تاریخ شروع')),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True, verbose_name='تاریخ پایان')),
                ('funding', models.DecimalField(blank=True, db_column='Funding', decimal_places=2, max_digits=12, null=True, verbose_name='بودجه')),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'پژوهش',
                'verbose_name_plural': 'پژوهش\u200cها',
                'db_table': 'research',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchParticipant',
            fields=[
                ('participationid', models.AutoField(db_column='ParticipationID', primary_key=True, serialize=False)),
                ('participantid', models.IntegerField(blank=True, db_column='ParticipantID', null=True, verbose_name='شناسه شرکت\u200cکننده')),
                ('participanttype', models.CharField(db_column='ParticipantType', max_length=9, verbose_name='نوع شرکت\u200cکننده')),
                ('role', models.CharField(blank=True, db_column='Role', max_length=50, null=True, verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'شرکت\u200cکننده پژوهش',
                'verbose_name_plural': 'شرکت\u200cکنندگان پژوهش',
                'db_table': 'researchparticipant',
                'managed': False,
            },
        ),
    ]
