# Generated by Django 5.2.8 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('tuitionid', models.AutoField(db_column='TuitionID', primary_key=True, serialize=False)),
                ('semester', models.CharField(db_column='Semester', max_length=14, verbose_name='ترم')),
                ('year', models.TextField(blank=True, db_column='Year', null=True, verbose_name='سال')),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ')),
                ('paymentstatus', models.CharField(db_column='PaymentStatus', max_length=11, verbose_name='وضعیت پرداخت')),
                ('paymentdate', models.DateField(blank=True, db_column='PaymentDate', null=True, verbose_name='تاریخ پرداخت')),
                ('paymentmethod', models.CharField(blank=True, db_column='PaymentMethod', max_length=50, null=True, verbose_name='روش پرداخت')),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'شهریه',
                'verbose_name_plural': 'شهریه\u200cها',
                'db_table': 'tuition',
                'managed': False,
            },
        ),
    ]
